baseURL = 'https://www.mountaindreamercounseling.com/'
languageCode = 'en-us'
title = 'Mountain Dreamer Counseling, LLC'
theme = "paige"
[markup.highlight]
noclasses = false
style = "github"
[module]
  [[module.imports]]
    path = "github.com/willfaught/paige"
