baseURL = 'https://mohsenil85.github.io/mdc/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[markup.highlight]
noclasses = false
style = "github"
[module]
  [[module.imports]]
    path = "github.com/willfaught/paige"
